export const popularMovies = [
  {
    title: 'Continue Watching',
    data: [
      {
        contentType: 'movie',
        id: '1',
        title: 'Dolphin Tale',
        type: 'Adventure • Drama',
        image: 'https://picsum.photos/200/300',
        genreIds: ['kids', 'drama'],
      },
      {
        contentType: 'movie',
        id: '2',
        title: 'Example',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['kids', 'comedy'],
      },
      {
        contentType: 'movie',
        id: '3',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['comedy', 'family'],
      },
      {
        contentType: 'movie',
        id: '4',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['comedy', 'family'],
      },
      {
        contentType: 'movie',
        id: '5',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['drama', 'family'],
      },
      {
        contentType: 'movie',
        id: '6',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['family'],
      },
      {
        contentType: 'movie',
        id: '7',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['family'],
      },
      {
        contentType: 'movie',
        id: '8',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['drama'],
      },
      {
        contentType: 'movie',
        id: '9',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['family'],
      },
      {
        contentType: 'movie',
        id: '10',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['family'],
      },
      {
        contentType: 'movie',
        id: '11',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['family'],
      },
      {
        contentType: 'movie',
        id: '12',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['kids', 'family'],
      },
      {
        contentType: 'movie',
        id: '13',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['kids', 'drama'],
      },
      {
        contentType: 'movie',
        id: '14',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['kids'],
      },
      {
        contentType: 'movie',
        id: '15',
        title: 'Vampire Diaries',
        episode: 'S1 E3 - MOTHERS',
        image: 'https://picsum.photos/200/300',
        genreIds: ['kids'],
      },
    ],
  },
];

// Dummy genre data
export const genres = [
  {id: '1', name: 'Kids'},
  {id: '2', name: 'Family'},
  {id: '3', name: 'Comedy'},
  {id: '4', name: 'Drama'},
  // Add more genres as needed
];
